### ISSUE TITLE
支付回调验证失败

### ISSUE THREAD

**Issue by superlbr** [lodengo/alipay#23]
如果在subject里面放入中文，回调的时候会以乱码的形式存在，这个时候验证必定失败，java里面是params.put(name, new String (valueStr.getBytes("ISO-8859-1"),"UTF-8"))，不知道node里面怎么处理

**Comment by nearcode** [comment]
exports.md5Verify = function(prestr, sign, key){
    prestr = prestr + key;
    

> var mysgin = crypto.createHash('md5').update(prestr).digest("hex");

将上面改成下面就可以了
    

> var mysgin = crypto.createHash('md5').update(prestr, 'utf8').digest("hex");

**Comment by jojoin** [comment]
支付宝回调的时候报错：

ReferenceError: createLinkstring is not defined
    at AlipayNotify.getSignVeryfy (/data/website/sffice/node_modules/alipay/lib/alipay_notify.class.js:107:18)
    at AlipayNotify.verifyNotify (/data/website/sffice/node_modules/alipay/lib/alipay_notify.class.js:48:27)
    at Alipay.create_direct_pay_by_user_notify (/data/website/sffice/node_modules/alipay/lib/alipay.js:417:15)
    at exports.alipay (/data/website/sffice/www/controller/pay/confirm.js:67:12)
    at Layer.handle [as handle_request] (/data/website/sffice/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/website/sffice/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/data/website/sffice/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/website/sffice/node_modules/express/lib/router/layer.js:95:5)
    at /data/website/sffice/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/data/website/sffice/node_modules/express/lib/router/index.js:330:12)

**Comment by yuk320** [comment]
上面这个也要改 改 core_funcs.createLinkstring

**Comment by yuk320** [comment]
反正坑众多，我现在加了 手机支付的 勉强才调通
